version: '3'

services:

  fogbus2-game_of_life29:
    # image: fogbus2-game_of_life29
    image: cloudslab/fogbus2-game_of_life29
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife29/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

