version: '3'

services:

  ocr:
    container_name: ocr
    image: ocr
    build:
      context: ../../
      dockerfile: ./tasks/OCR/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"

