version: '3'

services:

  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./sources:/workplace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"
    restart: unless-stopped

