version: '3'

services:

  game_of_life12:
    container_name: game_of_life12
    image: game_of_life12
    build:
      context: ../../
      dockerfile: ./tasks/GameOfLife12/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"

