version: '3'

services:

  game_of_life6:
    container_name: game_of_life6
    image: game_of_life6
    build:
      context: ../../
      dockerfile: ./tasks/GameOfLife6/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"

