version: '3'

services:

  remote-logger:
    container_name: remote-logger
    image: remote-logger
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./sources:/workplace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    ports:
      - 5001:5001
    network_mode: "host"
