version: '3'

services:

  remote-logger:
    container_name: remote-logger
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/workplace
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    ports:
      - 5001:5001
    restart: unless-stopped
