version: '3'

services:

  fogbus2-ocr:
    # image: fogbus2-ocr
    image: cloudslab/fogbus2-ocr
    build:
      context: ../../
      dockerfile: dockerFiles/OCR/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

