version: '3'

services:

  game_of_life29:
    container_name: game_of_life29
    image: game_of_life29
    build:
      context: ../../
      dockerfile: ./tasks/GameOfLife29/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"

