version: '3'

services:

  fogbus2-game_of_life33:
    # image: fogbus2-game_of_life33
    image: cloudslab/fogbus2-game_of_life33
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife33/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

