version: '3'

services:

  master:
    container_name: master
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        RemoteLoggerIP: ${RemoteLoggerIP}
        RemoteLoggerPort: ${RemoteLoggerPort}
    volumes:
      - ./:/workplace
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    ports:
      - 5000:5000
    restart: unless-stopped
