version: '3'

services:

  master:
    container_name: master
    image: master
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./sources/:/workplace
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    ports:
      - 5000:5000
    network_mode: "host"
    restart: unless-stopped
