version: "3"

services:
  mariadb:
    image: "mariadb:10.5.9"
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql/
    environment:
      TZ: Australia/Melbourne
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - 3306:3306
    restart: unless-stopped
