version: '3'

services:

  fogbus2-game_of_life16:
    # image: fogbus2-game_of_life16
    image: cloudslab/fogbus2-game_of_life16
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife16/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

