version: '3'

services:

  fogbus-master: 
    container_name: fogbus-master
    build: 
      context: ../../
      dockerfile: ./containers/master/Dockerfile
    volumes: 
        - ../../src/master:/config/www/
        - ../../src/nginx:/config/nginx
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    ports:
      - 80:80
    restart: unless-stopped

  database:
    image: linuxserver/mariadb
    container_name: fogbus-database
    volumes: 
      - ../../src/mysql-dump:/config/initdb.d/
      - ./data/db:/config
    ports:
      - "3306:3306"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
      MYSQL_DATABASE: users
      MYSQL_USER: fogbus
      MYSQL_PASSWORD: fogbus
    restart: unless-stopped
