from .base import BaseTask
from .blurAndPHash import BlurAndPHash
from .colorTracking import ColorTracking
from .eyeDetection import EyeDetection
from .faceDetection import FaceDetection
from .gameOfLife import GameOfLife
from .gameOfLife0 import GameOfLife0
from .gameOfLife1 import GameOfLife1
from .gameOfLife10 import GameOfLife10
from .gameOfLife11 import GameOfLife11
from .gameOfLife12 import GameOfLife12
from .gameOfLife13 import GameOfLife13
from .gameOfLife14 import GameOfLife14
from .gameOfLife15 import GameOfLife15
from .gameOfLife16 import GameOfLife16
from .gameOfLife17 import GameOfLife17
from .gameOfLife18 import GameOfLife18
from .gameOfLife19 import GameOfLife19
from .gameOfLife2 import GameOfLife2
from .gameOfLife20 import GameOfLife20
from .gameOfLife21 import GameOfLife21
from .gameOfLife22 import GameOfLife22
from .gameOfLife23 import GameOfLife23
from .gameOfLife24 import GameOfLife24
from .gameOfLife25 import GameOfLife25
from .gameOfLife26 import GameOfLife26
from .gameOfLife27 import GameOfLife27
from .gameOfLife28 import GameOfLife28
from .gameOfLife29 import GameOfLife29
from .gameOfLife3 import GameOfLife3
from .gameOfLife30 import GameOfLife30
from .gameOfLife31 import GameOfLife31
from .gameOfLife32 import GameOfLife32
from .gameOfLife33 import GameOfLife33
from .gameOfLife34 import GameOfLife34
from .gameOfLife35 import GameOfLife35
from .gameOfLife36 import GameOfLife36
from .gameOfLife37 import GameOfLife37
from .gameOfLife38 import GameOfLife38
from .gameOfLife39 import GameOfLife39
from .gameOfLife4 import GameOfLife4
from .gameOfLife40 import GameOfLife40
from .gameOfLife41 import GameOfLife41
from .gameOfLife42 import GameOfLife42
from .gameOfLife43 import GameOfLife43
from .gameOfLife44 import GameOfLife44
from .gameOfLife45 import GameOfLife45
from .gameOfLife46 import GameOfLife46
from .gameOfLife47 import GameOfLife47
from .gameOfLife48 import GameOfLife48
from .gameOfLife49 import GameOfLife49
from .gameOfLife5 import GameOfLife5
from .gameOfLife50 import GameOfLife50
from .gameOfLife51 import GameOfLife51
from .gameOfLife52 import GameOfLife52
from .gameOfLife53 import GameOfLife53
from .gameOfLife54 import GameOfLife54
from .gameOfLife55 import GameOfLife55
from .gameOfLife56 import GameOfLife56
from .gameOfLife57 import GameOfLife57
from .gameOfLife58 import GameOfLife58
from .gameOfLife59 import GameOfLife59
from .gameOfLife6 import GameOfLife6
from .gameOfLife60 import GameOfLife60
from .gameOfLife61 import GameOfLife61
from .gameOfLife7 import GameOfLife7
from .gameOfLife8 import GameOfLife8
from .gameOfLife9 import GameOfLife9
from .kineticEnergy0 import KineticEnergy0
from .kineticEnergy1 import KineticEnergy1
from .kineticEnergy2 import KineticEnergy2
from .kineticEnergy3 import KineticEnergy3
from .naiveFormula0 import NaiveFormula0
from .naiveFormula1 import NaiveFormula1
from .naiveFormula2 import NaiveFormula2
from .naiveFormula3 import NaiveFormula3
from .ocr import OCR
from .testTask import TestTask
