version: '3'

services:

  fogbus2-game_of_life2:
    # image: fogbus2-game_of_life2
    image: cloudslab/fogbus2-game_of_life2
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife2/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

