from .base import ApplicationUserSide
from .colorTracking import ColorTracking
from .faceAndEyeDetection import FaceAndEyeDetection
from .faceDetection import FaceDetection
from .gameOfLifeParallelized import GameOfLifeParallelized
from .gameOfLifePyramid import GameOfLifePyramid
from .gameOfLifeSerialized import GameOfLifeSerialized
from .naiveFormulaParallelized import NaiveFormulaParallelized
from .naiveFormulaSerialized import NaiveFormulaSerialized
from .videoOCR import VideoOCR
