version: '3'

services:

  game_of_life56:
    container_name: game_of_life56
    image: game_of_life56
    build:
      context: ../../
      dockerfile: ./tasks/GameOfLife56/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"

