from enum import Enum
from enum import unique


@unique
class MessageSubType(Enum):
    NONE = ''
    DEFAULT = 'default'
    EXPERIMENTAL = 'experimental'
    REGISTER = 'register'
    REGISTERED = 'registered'
    RUN_TASK_EXECUTOR = 'runTaskExecutor'
    LOOKUP = 'lookup'
    READY = 'ready'
    SERVICE_READY = 'serviceReady'
    SENSORY_DATA = 'sensoryData'
    INTERMEDIATE_DATA = 'intermediateData'
    WAITING = 'waiting'
    WAIT = 'wait'
    REUSE = 'reuse'
    RESULT = 'result'
    FINAL_RESULT = 'finalResult'
    EXIT = 'exit'
    STOP = 'stop'
    GET_PROFILES = 'getProfiles'
    PROFILES_INFO = 'profilesInfo'
    INIT_NEW_MASTER = 'initNewMaster'
    MEDIAN_RECEIVED_PACKET_SIZE = 'medianReceivedPacketSize'
    MEDIAN_PROCESSING_TIME = 'medianProcessingTime'
    HOST_RESOURCES = 'hostResources'
    RESPONSE_TIME = 'responseTime'
    DELAYS = 'delays'
    CONTAINER_IMAGES_AND_RUNNING_CONTAINERS = 'containerImagesAndRunningContainers'
    LATENCY = 'latency'
    REQUEST_PROFILES = 'requestProfiles'
    ALL_RESOURCES_PROFILES = 'allResourcesProfiles'
    REQUEST_ACTORS_INFO = 'requestActorsInfo'
    ACTORS_INFO = 'actorsInfo'
    ADVERTISE_MASTER = 'advertiseMaster'
    DATA_RATE_TEST = 'dataRateTest'
    LATENCY_TEST = 'latencyTest'
    CONNECT_TO_NEW_MASTER = 'connectToNewMaster'
    TIME_DIFFERENCE = 'timeDifference'
    ACTORS_COUNT = 'actorsCount'
    PROBE = 'probe'
    NO_ACTOR = 'noActor'
    PROFILES = 'profiles'
