version: '3'

services:

  fogbus2-game_of_life31:
    # image: fogbus2-game_of_life31
    image: cloudslab/fogbus2-game_of_life31
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife31/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

