version: '3'

services:

  fogbus2-game_of_life26:
    # image: fogbus2-game_of_life26
    image: cloudslab/fogbus2-game_of_life26
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife26/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

