version: '3'

services:

  game_of_life36:
    container_name: game_of_life36
    image: game_of_life36
    build:
      context: ../../
      dockerfile: ./tasks/GameOfLife36/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode: "host"

