version: '3'

services:

  fogbus2-game_of_life36:
    # image: fogbus2-game_of_life36
    image: cloudslab/fogbus2-game_of_life36
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife36/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

