version: '3'

services:

  fogbus2-game_of_life5:
    # image: fogbus2-game_of_life5
    image: cloudslab/fogbus2-game_of_life5
    build:
      context: ../../
      dockerfile: dockerFiles/GameOfLife5/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    network_mode:
      host

